[project]
name = "bookstore"
version = "1.0.0"
description = "The basic bookstore app built in Flask."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"